# Generated by Django 3.0.5 on 2020-07-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_review', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
    ]
