# Generated by Django 3.0.5 on 2020-07-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_titles', '0002_auto_20200713_0635'),
        ('api_review', '0006_auto_20200715_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ManyToManyField(blank=True, null=True, to='api_titles.Title', verbose_name='Заголовок'),
        ),
    ]
