# Generated by Django 3.0.5 on 2020-07-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_review', '0007_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
    ]
